GET http://localhost:5000/
Content-Type: application/json
###
 
GET http://localhost:5000/details/63f341e117a9540b9ff75a60
Content-Type: application/json
###

GET http://localhost:5000/cv/details/63f33c80a2af566a3ee58cd1
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWI0ZDgxMDIwNDQ5NjZjOGVhZDdkOCIsInVzZXJuYW1lIjoidGhhbzEiLCJlbWFpbCI6InBoMTAwN0BnbWFpbC5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3Njg4Njc0MSwiZXhwIjoxNjc2OTczMTQxfQ.eDMQDAoMDGcEWlAeeU55mNhPW_L_eGpKH78ZwjaeDqQ

###

POST http://localhost:5000/create
Content-Type: application/json
{
   "major": "CNTT",
   "name":"phong",
   "email": "phong1007@gmail.com",
   "nameschool": "hutech",
   "namecompany": "FPT",
   "url": "abc"
}
###

GET http://localhost:5000/cv
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZmVjMzY4ZjM3OTZkNzg4ODMxYjg1YSIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJwaDEwMDdAZ21haWwuY29tIiwicm9sZSI6IlN0dWRlbnQiLCJpYXQiOjE2NzgzNzQzNDQsImV4cCI6MTY3ODQ2MDc0NH0.z38Vi-153Qsjt3x9L9ax4wdgMq_q0r6unEAM8q3tCfM
###

GET http://localhost:5000/profile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWFkMWQxNTM5NWZhYWI5NWYxNDc0MCIsInVzZXJuYW1lIjoidGhhbzEwMTExMTEiLCJlbWFpbCI6InBob2ExMjM0QGdtYWlsLmNvbSIsInJvbGUiOiJTdHVkZW50IiwiaWF0IjoxNjc5NDgxNTU1LCJleHAiOjE2Nzk1Njc5NTV9.jCW9unSW5qVRUdR2MoQbbEmRjcOgRzeA_qqwidcuets
###


PUT http://localhost:5000/update-profile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWFkMWQxNTM5NWZhYWI5NWYxNDc0MCIsInVzZXJuYW1lIjoidGhhbzEwMTExMTEiLCJlbWFpbCI6InBob2ExMjM0QGdtYWlsLmNvbSIsInJvbGUiOiJTdHVkZW50IiwiaWF0IjoxNjc5NDgxNTU1LCJleHAiOjE2Nzk1Njc5NTV9.jCW9unSW5qVRUdR2MoQbbEmRjcOgRzeA_qqwidcuets

{
   "gender": "Nam",
   "studentname": "studentname",
   "academicyear": "academicyear",
   "address": "tphcm",
   "code": "1231312",
   "major": "cntt", 
   "school": "school"
}
###    

POST http://localhost:5000/setting/change-password
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZmVjNWE3ZTQzMmQ3ZGFiMzc0NTY0MCIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJuZmUwOTkzMEBuZXppZC5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3OTIyMjA2MiwiZXhwIjoxNjc5MzA4NDYyfQ.aI2l2k7UHxOhjvB8O2OkPFNnKbZYVcbEJLfhsOptqW8

{
   "oldPass": "1231",
   "newPass": "123",
   "cfmPass": "123"
}
###


PUT http://localhost:5000/details/6410231f159fbc02d8454c60
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTI4ODdmNjY3ZjVhNGVjMGZmZDI3YiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJ6eWc4MTI2OEBvbWVpZS5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3OTA0NzY0MywiZXhwIjoxNjc5MTM0MDQzfQ.-6fRKJwRu8qkw_FSSazmaFSdWbdMd9dbwAYE1OES0vA

###



PUT http://localhost:5000/details/delete-fa/63f341e117a9540b9ff75a60
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTI4ODdmNjY3ZjVhNGVjMGZmZDI3YiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJ6eWc4MTI2OEBvbWVpZS5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3OTM4MDA3MSwiZXhwIjoxNjc5NDY2NDcxfQ.htupGfyNrXwMiadkgzc6HMkic84sN5wLckCYY1HfqIM

###

GET  http://localhost:5000/a
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTI4ODdmNjY3ZjVhNGVjMGZmZDI3YiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJ6eWc4MTI2OEBvbWVpZS5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3OTM4NjQ2NiwiZXhwIjoxNjc5NDcyODY2fQ.XyuTMc1pL_Airs3p71vAM6WUIO7JEjeOu5isx1X0Oj8

###


GET http://localhost:5000/listmajor
Content-Type: application/json
### lisst major


GET http://localhost:5000/listcompany
Content-Type: application/json
### lisst company