POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "aitech",
    "email": "123111@zslsz.com",
    "password": "123",
    "confpassword": "123",
    "phonenumber": "22222",
    "academicyear": "2019",
    "gender": "nam",
    "school": "hutech"
    
}
####
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "aitech@gmail.com",
    "password": "123"

}

####
# 

POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
    "email": "ph1007@gmail.com",
    "newpassword": "321111111",
    "confpassword": "321111111"

}
###

POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
    "email": "ph1007@gmail.com",
    "newpassword": "123",
    "confpassword": "123"

}