POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "aitech",
    "email": "phongphan123@zslsz.com",
    "password": "123",
    "confpassword": "123",
    "phonenumber": "31251231222",
    "academicyear": "2019",
    "gender": "nam",
    "school": "hutech"
    
}
####
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "phongphan123@zslsz.com",
    "password": "123"

}

####
# 

POST http://localhost:5000/auth/reset-password
Content-Type: application/json

{
    "email": "bcu96623@zslsz.com"
}
###

GET http://localhost:5000/auth/confirm/bbm05118@zslsz.com
Content-Type: application/json

####

POST http://localhost:3000/auth/reset-password/alo19703@zslsz.com
Content-Type: application/json

{
    "oldPass": "123",
    "newPass": "1233",
    "cfmPass": "1233"

}
###

POST http://localhost:5000/auth/forgot-password
Content-Type: application/json

{
    "email": "yks11031@omeie.com"
}
###
POST http://localhost:5000/auth/forgot-password/yks11031@omeie.com
Content-Type: application/json

{
    "newPass": "333",
    "cfmPass": "333"

}