
# ///request Account
GET http://localhost:5000/admin/account
Content-Type: application/json
###
POST http://localhost:5000/admin/account/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTRiZWE1NGViZWE5NzMyNmI1ZjBmYyIsInVzZXJuYW1lIjoidGhhbzEiLCJyb2xlIjoiU3R1ZGVudCIsImlhdCI6MTY3NjExOTM4NiwiZXhwIjoxNjc2MTE5OTg2fQ.wV1iIGABhLsMWvBmA-W-f2Up7QAEs8SEH1snoXoTS1Q

{
    "username": "thao1011111",
    "email": "tt2007777@gmail.com",
    "password": "123",
    "confpassword": "123",
    "phonenumber": "221199777",
    "role": "Admin"
}
###
GET http://localhost:5000/admin/account/details/63e4be71844ea261a211fbb5
Content-Type: application/json
####
PUT http://localhost:5000/admin/account/details/63e5efd55eb9672311ca3f38
Content-Type: application/json

{
    "username": "thao12131201111",
    "email": "tt1007@gmail.com",
    "password": "123",
    "confpassword": "123",
    "phonenumber": "1221199",
    "role": "Admin"
}
###
DELETE  http://localhost:5000/admin/account/63e4c81aa487f672585430ba
Content-Type: application/json


####



///Request School
GET http://localhost:5000/admin/school
###
POST http://localhost:5000/admin/school/create
Content-Type: application/json

{
    "nameschool": "abc",
    "emailschool": "abzyxz@gmail.com",
    "websiteschool": "abcxzx.com.vn",
    "phoneschool": "999991111",
    "location": "tphcm"
}
###
PUT http://localhost:5000/admin/company/details/63ba3fab13cdb53bcaea292c
Content-Type: application/json

{
    "nameschool": "abc",
    "emailschool": "bachkhoa@gmail.com",
    "websiteschool": "bachkhoa.com.vn",
    "phoneschool": "912991111",
    "location": "tphcm"
}
###
DELETE  http://localhost:5000/admin/company/63ba3fab13cdb53bcaea292c
Content-Type: application/json
###



///Request Company
GET http://localhost:5000/admin/company
###
POST http://localhost:5000/admin/company/create
Content-Type: application/json
{
    "namecompany": "abc",
    "emailcompany": "abc@gmail.com",
    "websitecompany": "abc.com.vn",
    "phonecompany": "99999"
}
####
PUT http://localhost:5000/admin/company/details/63e60421fe5acf127d621092
Content-Type: application/json
####
DELETE  http://localhost:5000/admin/company/63e60421fe5acf127d621092
Content-Type: application/json

###


///Request Major
GET http://localhost:5000/admin/major
###
POST http://localhost:5000/admin/major/create
Content-Type: application/json

{
    "nameMajor": "abc"
}
###
PUT http://localhost:5000/admin/company/details/63e9a2c881f9d64ac1b5eef3
Content-Type: application/json

{
    "namemajor": "tâm lý học"
}
###
DELETE  http://localhost:5000/admin/company/63e9a2c881f9d64ac1b5eef3
Content-Type: application/json
###