GET http://localhost:5000/uni/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlhYjMzMzU0ODBiNDllNWEwYmUwYiIsInVzZXJuYW1lIjoiaHV0ZWNoIiwiZW1haWwiOiJjY2NAZ21haWwuY29tIiwicm9sZSI6IlNjaG9vbCIsImlhdCI6MTY3NjQ2MDU5NSwiZXhwIjoxNjc2NTQ2OTk1fQ.sy9CqzW7n3mx9skiqCfCSFK9Yc2o-YePHcBSLrIRlbg
####
get http://localhost:5000/uni/details/63eb4d8102044966c8ead7da
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlhYjMzMzU0ODBiNDllNWEwYmUwYiIsInVzZXJuYW1lIjoiaHV0ZWNoIiwiZW1haWwiOiJjY2NAZ21haWwuY29tIiwicm9sZSI6IlNjaG9vbCIsImlhdCI6MTY3NjQ2MDU5NSwiZXhwIjoxNjc2NTQ2OTk1fQ.sy9CqzW7n3mx9skiqCfCSFK9Yc2o-YePHcBSLrIRlbg

####

PUT http://localhost:5000/uni/details/63eb4d8102044966c8ead7da
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTlhYjMzMzU0ODBiNDllNWEwYmUwYiIsInVzZXJuYW1lIjoiaHV0ZWNoIiwicm9sZSI6IlNjaG9vbCIsImlhdCI6MTY3NjQ1ODgzNSwiZXhwIjoxNjc2NTQ1MjM1fQ.fjSNET1mrI5klp2hmwyIw9RB_-A-Qbz9-04HXJ19I_Q

{
  "studentname": "phong123123",
  "studentemail": "phong123123@gmail.com",
  "studentphone": "123123",
  "academicyear": "2018",
  "address": "tphcm",
  "code": 1911062239,
  "gender": "nu",
  "major": "cntt",
  "school": "hutech",
  "verify": true
}