GET http://localhost:5000/company
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjg5NGU5ODAyZGFlM2VjYTcwYzQ4ZiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJwaG9uZzdAZ21haWwuY29tIiwicm9sZSI6IkNvbXBhbnkiLCJpYXQiOjE2NzgwOTEyNTUsImV4cCI6MTY3ODE3NzY1NX0.4d9unzu1JrHPdikqL5L-IbAXNwjyF8fLr5qpCQm7Ies
###
 
GET http://localhost:5000/company/list-cv
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjg5NGU5ODAyZGFlM2VjYTcwYzQ4ZiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJwaG9uZzdAZ21haWwuY29tIiwicm9sZSI6IkNvbXBhbnkiLCJpYXQiOjE2Nzc2NzkxMDAsImV4cCI6MTY3Nzc2NTUwMH0.kRsYpG6ndqR36O5b5yaNnRTKJAcnTfdcvRVtQfvZZD4
#### 
GET http://localhost:5000/company/details/63eb615d91d27de2f55b033b
Content-Type: application/json
###

POST http://localhost:5000/company/list-cv/details/63eb615d91d27de2f55b033b/send-email
Content-Type: application/json

{
  "fromEmail": "phandinhphong258@gmail.com",
  "toEmail": "uka56346@nezid.com",
  "subject": "mail confirm",
  "message": "you passed"
}
###

GET http://localhost:5000/company/list-cv/details/63f33dbea2af566a3ee58cd3
Content-Type: application/json
###


POST http://localhost:5000/company/create
Content-Type: application/json

{
  "namecompany": "fpt",
  "benifit": "không có"
}
###
DELETE  http://localhost:5000/company/64104752a178beae8908e393
Content-Type: application/json

####
PUT http://localhost:5000/company/details/6402bd265a9da47499ec6f78
Content-Type: application/json

{
  "benefit": "100tr 1 tháng"

}
###
GET http://localhost:5000/company/profile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjg5NGU5ODAyZGFlM2VjYTcwYzQ4ZiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJhaXRlY2hAZ21haWwuY29tIiwicm9sZSI6IkNvbXBhbnkiLCJpYXQiOjE2Nzg1MDQyNTEsImV4cCI6MTY3ODU5MDY1MX0.fGFRsM5_OmxN5XdABus2k_6tKI_K5Dr39LEoS2dVzuE
###


PUT http://localhost:5000/company/update-profile
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjg5NGU5ODAyZGFlM2VjYTcwYzQ4ZiIsInVzZXJuYW1lIjoiYWl0ZWNoIiwiZW1haWwiOiJhaXRlY2hAZ21haWwuY29tIiwicm9sZSI6IkNvbXBhbnkiLCJpYXQiOjE2Nzg1MDQyNTEsImV4cCI6MTY3ODU5MDY1MX0.fGFRsM5_OmxN5XdABus2k_6tKI_K5Dr39LEoS2dVzuE

{
  "introduce": "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV) là ngân hàng hàng đầu tại Việt Nam, hoạt động kinh doanh trong nhiều lĩnh vực như: Ngân hàng, Bảo hiểm, Chứng khoán. Với hơn 25.000 cán bộ nhân viên, BIDV nhận thức được rằng nguồn nhân lực là một nhân tố quan trọng hàng đầu cho sự phát triển và thành công của tổ chức. Vì vậy, một trong những mục tiêu quan trọng nhất của BIDV là phải xây dựng, duy trì và phát triển đội ngũ nhân viên đảm bảo đủ về số lượng và chất lượng để thực hiện thắng lợi các mục tiêu, chiến lược kinh doanh của hệ thống. ",
  "slogan": "DỄ DÀNG - NHANH CHÓNG - CHUẨN MỰC - TÍN NGHĨA"
}

###